name: alibaba
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-alibaba
  schedule:
    - cron: '0 6 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: https://registry-intl.ap-southeast-1.aliyuncs.com
          OCI_USERNAME: ${{ secrets.ALIBABA_USERNAME }}
          OCI_PASSWORD: ${{ secrets.ALIBABA_PASSWORD }}
          OCI_NAMESPACE: ocitest/ocitest-docker
          OCI_TAG_NAME: 1.16.1-debian-10-r77
          OCI_MANIFEST_DIGEST: sha256:d6ac96bbd7878961c998162539fadb50ae830406300f6912e28d8b8bbc8778c3
          OCI_BLOB_DIGEST: sha256:310277bda89b09908114f4f227feada9d53760892069e87a4461ad8c84f2cfbf
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/alibaba.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
