name: ecr
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-ecr
  schedule:
    - cron: '0 6 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Amazon access token
        run: |
          export ECR_ACCESS_TOKEN="$(aws --region=us-east-1 ecr get-login --no-include-email | awk '{print $6}')"
          echo "::add-mask::${ECR_ACCESS_TOKEN}"
          echo "::set-env name=ECR_ACCESS_TOKEN::${ECR_ACCESS_TOKEN}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: https://044887301101.dkr.ecr.us-east-1.amazonaws.com
          OCI_USERNAME: AWS
          OCI_PASSWORD: ${{ env.ECR_ACCESS_TOKEN }}
          OCI_NAMESPACE: ocitest
          #OCI_TAG_NAME: 1.16.1-debian-10-r77
          #OCI_MANIFEST_DIGEST: sha256:d6ac96bbd7878961c998162539fadb50ae830406300f6912e28d8b8bbc8778c3
          #OCI_BLOB_DIGEST: sha256:310277bda89b09908114f4f227feada9d53760892069e87a4461ad8c84f2cfbf
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/ecr.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
