version: 0.1
log:
  level: debug
storage:
    delete:
      enabled: true
    filesystem:
        rootdirectory: /tmp/registry
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
