name: quay

on:
  push:
    branches:
      - trigger-job-05

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'
      - name: run tests against quay.io
        run: ci/ci-quay.sh
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      - name: Ensure branch
        run: git config --global user.name "$GITHUB_ACTOR" && git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && (git checkout -b trigger-job-06 || true ) && git fetch origin trigger-job-06 && git merge --allow-unrelated-histories -s recursive -X theirs origin/trigger-job-06 && git fetch origin trigger-job-05 && git merge --allow-unrelated-histories -s recursive -X theirs origin/trigger-job-05
        if: always()
      - name: Regen readme
        run: echo -e "$(sed '$ d' README.md )\n05 $(date -u +'%Y-%m-%dT%H:%M:%SZ') ${GITHUB_SHA}" > README.md
        if: always()
      - name: Trigger job 06
        uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: Trigger job 06
          branch: trigger-job-06
          file_pattern: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()