name: acr
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-acr
  schedule:
    - cron: '0 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: https://bloodorange.azurecr.io
          OCI_NAMESPACE: bloodorange/oci-conformance-test
          OCI_USERNAME: ${{ secrets.ACR_USERNAME }}
          OCI_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/acr.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
