name: docker-distribution

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repo source code
        uses: actions/checkout@master
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'
      - name: run tests against docker/distribution
        run: ci/ci-docker-dist.sh
      - name: git pull
        run: git pull -f
        if: always()
      - name: commit HTML report back to git
        uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: Upload docker/distribution report
          branch: master
          file_pattern: results/report-docker-dist.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
