name: docker-distribution
on:
  repository_dispatch:
    types: manual-trigger
  schedule:
    - cron: '0 * * * *'
jobs:
  run:
    services:
      distribution:
        image: docker.io/registry:2.7.1
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: bloodorangeio/oci-test-action@v1.0.0-alpha.2
        env:
          OCI_ROOT_URL: http://distribution:5000
          OCI_NAMESPACE: bloodorange/oci-conformance-test
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/docker-dist.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
