name: dockerhub
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: bloodorangeio/oci-test-action@v1.0.0-alpha.2
        env:
          OCI_ROOT_URL: https://registry-1.docker.io
          OCI_NAMESPACE: bloodorangeio/oci-conformance-test
          OCI_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          OCI_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/dockerhub.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
