name: dockerhub-newsetup
on:
  push:
    branches:
      - initial-setup
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: bloodorangeio/distribution-spec@split-tests
        env:
          OCI_ROOT_URL: https://registry-1.docker.io
          OCI_NAMESPACE: bloodorangeio/oci-conformance-test
          OCI_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          OCI_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/dockerhub-newsetup.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
