name: gcr-split-tests
on:
  push:
    branches:
      - split-testsREMOVEMETOTRIGGER
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Google access token
        run: |
          echo ${GCLOUD_SERVICE_KEY} | base64 -d > ./credentials.json
          trap "rm -f ./credentials.json" EXIT
          gcloud auth activate-service-account ociaccessb@helmsummit.iam.gserviceaccount.com --key-file="./credentials.json" --project=helmsummit
          export GCLOUD_ACCESS_TOKEN="$(gcloud auth print-access-token)"
          echo "::add-mask::${GCLOUD_ACCESS_TOKEN}"
          echo "::set-env name=GCLOUD_ACCESS_TOKEN::${GCLOUD_ACCESS_TOKEN}"
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Run OCI Distribution Spec conformance tests
        uses: bloodorangeio/distribution-spec@split-tests
        env:
          OCI_ROOT_URL: https://gcr.io
          OCI_NAMESPACE: helmsummit/myrepo
          OCI_USERNAME: oauth2accesstoken
          OCI_PASSWORD: ${{ env.GCLOUD_ACCESS_TOKEN }}
          OCI_TEST_PUSH: 0
          OCI_TEST_DISCOVERY: 0
          OCI_TEST_MANAGEMENT: 0
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/gcr-split-tests.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
