name: gcr
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-gcr
  schedule:
    - cron: '0 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: bloodorangeio/oci-test-action@bloodorange-fork
        env:
          OCI_ROOT_URL: https://gcr.io
          OCI_NAMESPACE: helmsummit/myrepo
          OCI_USERNAME: oauth2accesstoken
          OCI_PASSWORD: fakepassword # TODO: fix $(gcloud auth print-access-token)
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/gcr.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
