name: jcr-1
on:
  push:
    branches:
      - master
jobs:
  run:
    services:
      jcr:
        image: docker.bintray.io/jfrog/artifactory-jcr:latest
        ports:
          - 8081:8081
    runs-on: ubuntu-latest
    steps:
      - name: Wait for JCR to be ready
        run: timeout 200 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:${{ job.services.jcr.ports['8081'] }}/artifactory/api/system/ping)" != "200" ]]; do sleep 5; done' || false
      - name: Checkout Workspace
        uses: actions/checkout@v2
      - name: Apply conformance config to JCR
        run: curl -u admin:password -X POST -H "Content-type:application/xml" --data-binary "@$GITHUB_WORKSPACE/.github/config/jcr/artifactory.config.import.xml"  http://localhost:${{ job.services.jcr.ports['8081'] }}/artifactory/api/system/configuration
      - name: Run OCI Distribution Spec conformance tests
        uses: bloodorangeio/distribution-spec@master
        env:
          OCI_ROOT_URL: http://jcr:8081
          OCI_USERNAME: admin
          OCI_PASSWORD: password
          OCI_NAMESPACE: conformance-local/oci-conformance-test
          OCI_TEST_PULL: 1
          OCI_TEST_PUSH: 1
          OCI_TEST_CONTENT_DISCOVERY: 1
          OCI_TEST_CONTENT_MANAGEMENT: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 0
          OCI_DEBUG: 0
      - run: mkdir -p .out/ && mv {report.html,junit.xml} .out/
        if: always()
      - name: Upload test results zip as build artifact
        uses: actions/upload-artifact@v1
        with:
          name: oci-test-results-${{ github.sha }}
          path: .out/
        if: always()
