name: trow
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-trow
  schedule:
    - cron: '0 * * * *'
jobs:
  trow-setup:
    runs-on: ubuntu-latest
    run: |
      echo '#!/bin/sh' > ./custom-entrypoint.sh
      echo '/start-trow.sh --no-tls' >> ./custom-entrypoint.sh
      chmod +x ./custom-entrypoint.sh

  run:
    services:
      trow:
        image: containersol/trow:default
        options: -v ./custom-entrypoint:/custom-entrypoint.sh --entrypoint /custom-entrypoint.sh
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: http://trow:8000
          OCI_NAMESPACE: bloodorange/oci-conformance-test
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/trow.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
