name: trow
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-trow
  schedule:
    - cron: '0 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Start trow service
        run: |
          docker run -d --name=trow -p 8000:8000 containersol/trow:default --no-tls
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: http://localhost:8000
          OCI_NAMESPACE: bloodorange/oci-conformance-test
      - name: Stop trow service
        if: always()
        run: |
          docker rm -f trow
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/trow.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
