name: zot-auth

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'
      - name: run tests against zot-auth
        run: ci/ci-zot-auth.sh
