name: zot-split-tests
on:
  push:
    branches:
      - split-tests
jobs:
  run:
    services:
      zot:
        image: quay.io/bloodorange/trow:b54f366-fork
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: bloodorangeio/distribution-spec@split-tests
        env:
          OCI_ROOT_URL: http://zot:5000
          OCI_NAMESPACE: bloodorange/oci-conformance-test
          OCI_TEST_PUSH: 1
          OCI_TEST_DISCOVERY: 1
          OCI_TEST_CONTENT_MANAGEMENT: 1
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-distribution-conformance-results/zot-split-tests.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
